### ISSUE TITLE
Grafik relativ schlecht bei konstanter Framerate

### ISSUE THREAD

**Issue by CrazyJannis44** [arbobendik/web-ray-tracer#18]
Hallo,
ich bin einfach mal deiner Aufforderung, das einmal zu testen gefolgt und habe bemerk, dass die Qualität bei mir ziemlich schlecht ist. Die FPS sind konstant bei 60 wie ich es in meinen internen Systemeinstellungen habe. Meine Grafikkarte ist die Nvidia GeForce GTX 1060 6GB welche jetzt auch nicht grad die Neuste ist ;)

![grafik](https://user-images.githubusercontent.com/36644360/132917479-a96ce9d2-dd05-4f33-a7de-f518898b344e.png)

**Comment by arbobendik** [comment]
Vielen Dank für das Feedback. Im Browser wird vsync standardmäßig verwendet (deswegen konstant 60Hz). Man kann auf der Testseite über die Konsole das über die Library erzeugte Objekt "rt" ansteuern und damit viele Qualitätseinstellungen ändern um die Optik zu verbessern.
So kann man z.B. die Auflösung auf ein Doppeltes der Fenster Auflösung setzen mit rt.SCALE = 2 oder die Samplezahl pro Ray erhöhen mit rt.SAMPLES. Damit auch auf lowend Geräten die Testwebsite halbwegs flüssig läuft hab ich mich dazu entschieden standardmäßig die Auflösung auf die halbe Fenstergröße zu beschränken. Weitere wichtige Eigenschaften des rt Objekts sind z.B. rt.FILTER (boolean ob Filter verwendet werden soll), rt.QUEUE (verschachtelter Aufbau aller Objekte, die sichtbar sein sollen, mit allen dazugehörigen Eigenschaften), rt.TEXTURE für alle verwendeten Texturen, rt.NORMAL_TEXTURE für alle verwendeten Rauheitstexturen, rt. LIGHT für alle Punktlichtquellen (leuchtende Texturen, Emissives, kommen noch), rt.FOV (nicht standartisierte Einheit für das Sichtfeld) und rt.GI für Global Illumination.
